# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HistoryApplicationIOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'GoogleMaps'
  # Pods for HistoryApplicationIOS

  target 'HistoryApplicationIOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'HistoryApplicationIOSUITests' do
    # Pods for testing
  end

end
